name: Android Build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23' 

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Install Gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Setup Android NDK
        run: |
          # Устанавливаем стабильную версию NDK 25
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;25.2.9519653"
          # Экспортируем пути в системные переменные GitHub
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Build XrayCore (Go)
        run: |
          # Принудительно задаем пути для текущего процесса сборки
          export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653
          export PATH=$PATH:$(go env GOPATH)/bin
          
          # Инициализируем gomobile
          gomobile init
          
          # Даем права и запускаем сборку ядра
          chmod +x buildGo.sh
          ./buildGo.sh

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        # Добавляем флаг, чтобы не падать на проверках оформления (lint)
        run: ./gradlew assembleDebug -x lint --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
