name: Release CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: "arm"
            abi_id: 1
            abi_target: "armeabi-v7a"
            tag: "arm32"
          - arch: "arm64"
            abi_id: 2
            abi_target: "arm64-v8a"
            tag: "arm64"
          - arch: "386"
            abi_id: 3
            abi_target: "x86"
            tag: "x86"
          - arch: "amd64"
            abi_id: 4
            abi_target: "x86_64"
            tag: "amd64"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t build-container -f Dockerfile .

      - name: Compile APK
        run: |
          # Создаем локальную папку для вывода, чтобы не иметь проблем с правами /opt
          mkdir -p output
          docker run --rm \
            -v ${{ github.workspace }}/output:/dist \
            -e DIST_DIR='/dist' \
            -e RELEASE_TAG="${{ github.ref_name }}" \
            -e NATIVE_ARCH="${{ matrix.arch }}" \
            -e ABI_ID=${{ matrix.abi_id }} \
            -e ABI_TARGET="${{ matrix.abi_target }}" \
            -e KS_FILE="${{ secrets.KS_FILE }}" \
            -e KS_PASSWORD="${{ secrets.KS_PASSWORD }}" \
            -e KEY_ALIAS="${{ secrets.KEY_ALIAS }}" \
            -e KEY_PASSWORD="${{ secrets.KEY_PASSWORD }}" \
            build-container

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.tag }}-build
          path: output/

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-dist
          # Это скачает все артефакты из задания build в подпапки

      - name: Prepare assets
        run: |
          mkdir -p release-dist
          find all-dist -name "*.apk" -exec cp {} release-dist/ \;

      - name: Set VERSION_CODE
        run: |
          # Предполагается, что файл существует в репозитории
          VERSION_CODE=$(cat "app/versionCode.txt")
          ((VERSION_CODE += 4))
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          prerelease: false
          draft: false
          files: "release-dist/*.apk"
          body_path: "metadata/en-US/changelogs/${{ env.VERSION_CODE }}.txt"
